const fs = require('fs');
const path = 'src/pages/Attendance/AttendanceList.tsx';
let content = fs.readFileSync(path, 'utf8');

const replacements = [
  ['"Attendance Records"', '"Data Kehadiran"'],
  ['"Monitor daily attendance logs."', '"Pantau log kehadiran harian."'],
  ['"Add Record"', '"Tambah Data"'],
  ['"Academic Year"', '"Tahun Ajaran"'],
  ['"All Years"', '"Semua Tahun"'],
  ['"Major"', '"Jurusan"'],
  ['"All Majors"', '"Semua Jurusan"'],
  ['"Class"', '"Kelas"'],
  ['"All Classes"', '"Semua Kelas"'],
  ['"Attendance Event"', '"Kegiatan / Acara"'],
  ['"Select Event"', '"Pilih Acara"'],
  ['"Status"', '"Status"'],
  ['"All Statuses"', '"Semua Status"'],
  ['"Start Date"', '"Tanggal Mulai"'],
  ['"Start date"', '"Tanggal mulai"'],
  ['"End Date"', '"Tanggal Akhir"'],
  ['"End date"', '"Tanggal akhir"'],
  ['"Late Minutes Threshold"', '"Batas Menit Terlambat"'],
  ['"Minutes..."', '"Menit..."'],
  ['"Student Name / ID"', '"Nama Siswa / NIS"'],
  ['"Search by Student Name or ID..."', '"Cari berdasarkan Nama Siswa atau NIS..."'],
  ['"Create Attendance"', '"Buat Kehadiran"'],
  ['"User"', '"Pengguna"'],
  ['"Search and select student..."', '"Cari dan pilih pengguna..."'],
  ['"Date"', '"Tanggal"'],
  ['"Status Label"', '"Label Status"'],
  ['"Target Class (Optional)"', '"Kelas Tujuan (Opsional)"'],
  ['"Select class..."', '"Pilih kelas..."'],
  ['"Associated Event (Optional)"', '"Acara Terkait (Opsional)"'],
  ['"Select event..."', '"Pilih acara..."'],
  ['"Latitude"', '"Garis Lintang"'],
  ['"Longitude"', '"Garis Bujur"'],
  ['"Add some context..."', '"Tambahkan keterangan..."'],
  ['"Target Class"', '"Kelas Tujuan"'],
  ['"Select Class"', '"Pilih Kelas"'],
  ['"Associated Event"', '"Acara Terkait"'],
  ['"Clock In"', '"Jam Masuk"'],
  ['"Clock Out"', '"Jam Keluar"'],
  ['"Notes"', '"Catatan"'],
  ['"No photo provided"', '"Tidak ada foto"'],
  ['"No notes provided."', '"Tidak ada catatan."'],
  ['"Mode"', '"Mode"'],
  ['"Daily & Class"', '"Harian & Kelas"'],
  ['"Update Record"', '"Perbarui Data"'],
  ['"Cancel"', '"Batal"'],
  ['"Save Changes"', '"Simpan Perubahan"'],
  ['"Attendance record updated successfully"', '"Data kehadiran berhasil diperbarui"'],
  ['"Failed to update attendance record"', '"Gagal memperbarui data kehadiran"'],
  ['"Create Record"', '"Simpan Kehadiran"'],
  ['"Attendance created successfully"', '"Kehadiran berhasil disimpan"'],
  ['"Failed to create attendance"', '"Gagal menyimpan kehadiran"'],
  ['"Delete Record"', '"Hapus Data"'],
  ['"Are you sure you want to delete this attendance record? This action cannot be undone."', '"Apakah Anda yakin ingin menghapus data kehadiran ini? Tindakan ini tidak dapat dibatalkan."'],
  ['"Delete"', '"Hapus"'],
  ['"Record deleted successfully"', '"Data berhasil dihapus"'],
  ['"Failed to delete record"', '"Gagal menghapus data"'],
  ['"Attendance Details"', '"Detail Kehadiran"'],
  ['"Close"', '"Tutup"'],
  ['"Export Data"', '"Ekspor Data"'],
  ['"Import Data"', '"Impor Data"'],
  ['"Bulk Update"', '"Perbarui Massal"'],
  ['"Rows per page:"', '"Baris per halaman:"'],
  ['"of"', '"dari"'],
  ['"Previous"', '"Sebelumnya"'],
  ['"Next"', '"Selanjutnya"'],
  ['"No attendance records found"', '"Tidak ada data kehadiran yang ditemukan"'],
  ['"Clear Filters"', '"Hapus Filter"'],
  ['"Daily"', '"Harian"'],
  ['"Class Session"', '"Sesi Kelas"'],
  ['"Event"', '"Acara"']
];

for (const [search, replace] of replacements) {
  content = content.split(search).join(replace);
}

fs.writeFileSync(path, content, 'utf8');
console.log('Translated content successfully!');
